/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import dao.FuncionarioDAO;
import dao.ComprasDAO;
import dao.ProdutoDAO;
import dto.Funcionario;
import dto.ComprasDTO;
import dto.ProdutoDTO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author jedle
 */
public class ComprasVIEW extends javax.swing.JFrame {

    /**
     * Creates new form ComprasVIEW
     */
    public ComprasVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIDfornecimentoCompra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        btnLimparCompra = new javax.swing.JButton();
        btnCadastrarProduto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtQTDprodutoCompra = new javax.swing.JTextField();
        cbxFuncionarios1 = new javax.swing.JComboBox();
        cbxProduto = new javax.swing.JComboBox();
        txtCnpjFCompra = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtIDfornecimentoCompraBusca = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_identificadorProdutoCompraB = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnBuscarCompra = new javax.swing.JButton();
        btnLimparCompraBusca = new javax.swing.JButton();
        btnExcluirCompra = new javax.swing.JButton();
        btnAtualizarCompra = new javax.swing.JButton();
        txtQTDcompraBusca = new javax.swing.JTextField();
        txtCnpjFCompraBusca1 = new javax.swing.JFormattedTextField();
        txtCpfFCompraBusca = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("CPF Funcionario");

        jLabel2.setText("ID_Fornecimento");

        jLabel3.setText("Codigo Identificador Produto");

        jLabel5.setText("CNPJ_Fornecedor");

        jLabel51.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel51.setText("Cadastrar Compra");

        btnLimparCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar-limpo.png"))); // NOI18N
        btnLimparCompra.setText("Limpar");
        btnLimparCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCompraActionPerformed(evt);
            }
        });

        btnCadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mole.png"))); // NOI18N
        btnCadastrarProduto.setText("Cadastrar");
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantidade");

        txtQTDprodutoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQTDprodutoCompraActionPerformed(evt);
            }
        });

        cbxFuncionarios1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbxFuncionarios1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbxFuncionarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFuncionarios1ActionPerformed(evt);
            }
        });

        cbxProduto.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbxProdutoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbxProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProdutoActionPerformed(evt);
            }
        });

        try {
            txtCnpjFCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpjFCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnpjFCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel51))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cbxFuncionarios1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIDfornecimentoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel1))
                                        .addGap(18, 18, Short.MAX_VALUE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQTDprodutoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCnpjFCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(100, 100, 100)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnLimparCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCadastrarProduto)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(42, 42, 42))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxFuncionarios1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDfornecimentoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQTDprodutoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCnpjFCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        jLabel8.setText("ID_Fornecimento");

        jLabel9.setText("CPF Funcionario");

        jLabel12.setText("CNPJ_Fornecedor");

        jLabel13.setText("Codigo Identificador Produto");

        txt_identificadorProdutoCompraB.setBackground(new java.awt.Color(204, 204, 204));

        jLabel52.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel52.setText("Buscar Compra");

        jLabel14.setText("Quantidade");

        btnBuscarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/binoculars.png"))); // NOI18N
        btnBuscarCompra.setText("Buscar");
        btnBuscarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCompraActionPerformed(evt);
            }
        });

        btnLimparCompraBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar-limpo.png"))); // NOI18N
        btnLimparCompraBusca.setText("Limpar");
        btnLimparCompraBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCompraBuscaActionPerformed(evt);
            }
        });

        btnExcluirCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        btnExcluirCompra.setText("Deletar");
        btnExcluirCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirCompraActionPerformed(evt);
            }
        });

        btnAtualizarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/updated.png"))); // NOI18N
        btnAtualizarCompra.setText("Atualizar");
        btnAtualizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarCompraActionPerformed(evt);
            }
        });

        txtQTDcompraBusca.setBackground(new java.awt.Color(204, 204, 204));

        txtCnpjFCompraBusca1.setEditable(false);
        txtCnpjFCompraBusca1.setBackground(new java.awt.Color(204, 204, 204));
        try {
            txtCnpjFCompraBusca1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpjFCompraBusca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnpjFCompraBusca1ActionPerformed(evt);
            }
        });

        try {
            txtCpfFCompraBusca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfFCompraBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfFCompraBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtIDfornecimentoCompraBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarCompra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimparCompraBusca))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtCnpjFCompraBusca1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCpfFCompraBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(txtQTDcompraBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_identificadorProdutoCompraB, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnAtualizarCompra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExcluirCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel52)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel52)
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDfornecimentoCompraBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparCompraBusca)
                    .addComponent(btnBuscarCompra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_identificadorProdutoCompraB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCpfFCompraBusca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQTDcompraBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCnpjFCompraBusca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCompraActionPerformed

        txtCnpjFCompra.setText("");
        txtIDfornecimentoCompra.setText("");
        txtQTDprodutoCompra.setText("");

    }//GEN-LAST:event_btnLimparCompraActionPerformed

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed

        String CPFfuncionario, CodigoIdentificadorProduto, CNPJfornecedor, IDfornecimento, quantidadeCompra;

        CPFfuncionario = cbxFuncionarios1.getSelectedItem().toString();
        CodigoIdentificadorProduto = cbxProduto.getSelectedItem().toString();
        IDfornecimento = txtIDfornecimentoCompra.getText();
        quantidadeCompra = txtQTDprodutoCompra.getText();
        CNPJfornecedor = txtCnpjFCompra.getText();

        ComprasDTO novaCompra = new ComprasDTO();
        novaCompra.setCPFfuncionario(CPFfuncionario);
        novaCompra.setCNPJfornecedor(CNPJfornecedor);
        novaCompra.setIDfornecimento(IDfornecimento);
        novaCompra.setQuantidade(quantidadeCompra);
        novaCompra.setCodigoIdentificadorProduto(CodigoIdentificadorProduto);

        ComprasDAO novaCompradao = new ComprasDAO();
        boolean cadastrado = novaCompradao.cadastrarCompra(novaCompra);

        if (cadastrado) {
            JOptionPane.showMessageDialog(this, "Compra cadastrada com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar Compra. Verifique os dados e tente novamente.");
        }


    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void txtQTDprodutoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQTDprodutoCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQTDprodutoCompraActionPerformed

    private void btnBuscarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCompraActionPerformed

        String IDfornecimento = txtIDfornecimentoCompraBusca.getText(); // pegando os dados do ID do fornecimento digitado no respectivo campo de busca.

        // Verificar se o id fornecimento foi digitado
        if (!IDfornecimento.isEmpty()) {
            ComprasDAO compradao = new ComprasDAO();
            ComprasDTO compradto = compradao.buscarCompraPorID(IDfornecimento);

            // Verificar se encontrou a compra
            if (compradto != null) {
                // A compra foi encontrada, desta forma ele seta os valores dos campos com os dados da respectiva compra.

                txtCpfFCompraBusca.setText(compradto.getCPFfuncionario());
                txt_identificadorProdutoCompraB.setText(compradto.getCodigoIdentificadorProduto());
                txtCnpjFCompraBusca1.setText(compradto.getCNPJfornecedor());
                txtQTDcompraBusca.setText(compradto.getQuantidade());

                JOptionPane.showMessageDialog(null, "Compra encontrada!");
            } else {
                // O funcionário não foi encontrado
                JOptionPane.showMessageDialog(null, "Compra não encontrada!");
            }
        } else {
            // O ID de fornecimento não foi digitado
            JOptionPane.showMessageDialog(null, "Digite um ID de Fornecimento válido!");
        }


    }//GEN-LAST:event_btnBuscarCompraActionPerformed

    private void btnLimparCompraBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCompraBuscaActionPerformed

        txtIDfornecimentoCompraBusca.setText("");
        txtCpfFCompraBusca.setText("");
        txt_identificadorProdutoCompraB.setText("");
        txtCnpjFCompraBusca1.setText("");
        txtQTDcompraBusca.setText("");
    }//GEN-LAST:event_btnLimparCompraBuscaActionPerformed

    private void btnExcluirCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirCompraActionPerformed

        String IDfornecimento = txtIDfornecimentoCompraBusca.getText(); // Campo onde o usuário digita o CPF a ser excluído

        ComprasDAO compradao = new ComprasDAO();
        boolean excluido = compradao.excluirCompraPorIDfornecimento(IDfornecimento);

        if (excluido) {
            JOptionPane.showMessageDialog(this, "Compra excluída com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir compra. Verifique o ID de fornecimento e tente novamente.");
        }

    }//GEN-LAST:event_btnExcluirCompraActionPerformed

    private void btnAtualizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarCompraActionPerformed

        String IDfornecimento = txtIDfornecimentoCompraBusca.getText(); // Obtém o ID fornecimento digitado pelo usuário

        ComprasDAO compradao = new ComprasDAO();

// Busca a compra pelo id
        ComprasDTO compradto = compradao.buscarCompraPorID(IDfornecimento);

        if (compradto != null) {
            // Aqui você pode preencher os campos do formulário com os dados da compra, caso deseje

            // Atualiza os campos necessários no objeto ComprasDTO
            compradto.setQuantidade(txtQTDcompraBusca.getText());
            compradto.setCNPJfornecedor(txtCnpjFCompraBusca1.getText());
            compradto.setCodigoIdentificadorProduto(txt_identificadorProdutoCompraB.getText());
            compradto.setCPFfuncionario(txtCpfFCompraBusca.getText());
            compradto.setIDfornecimento(IDfornecimento);
            

            // Realiza a atualização da compra
            boolean atualizado = compradao.atualizarCompra(compradto);

            if (atualizado) {
                JOptionPane.showMessageDialog(this, "Compra atualizada com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar compra. Verifique os dados e tente novamente.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Compra não encontrada. Verifique o ID de fornecimento e tente novamente.");
        }


    }//GEN-LAST:event_btnAtualizarCompraActionPerformed

    private void txtCnpjFCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnpjFCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnpjFCompraActionPerformed

    private void cbxFuncionarios1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbxFuncionarios1AncestorAdded
        FuncionarioDAO funcionariodao = new FuncionarioDAO();
        List<Funcionario> lista1 = funcionariodao.listarFuncionarios();

        cbxFuncionarios1.removeAll();

        for (Funcionario funcionario : lista1) {
            cbxFuncionarios1.addItem(funcionario);

        }

    }//GEN-LAST:event_cbxFuncionarios1AncestorAdded

    private void cbxProdutoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbxProdutoAncestorAdded
        ProdutoDAO produtodao = new ProdutoDAO();
        List<ProdutoDTO> lista2 = produtodao.listarProdutos();

        cbxProduto.removeAll();

        for (ProdutoDTO produto : lista2) {
            cbxProduto.addItem(produto);

        }


    }//GEN-LAST:event_cbxProdutoAncestorAdded

    private void cbxFuncionarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFuncionarios1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxFuncionarios1ActionPerformed

    private void txtCnpjFCompraBusca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnpjFCompraBusca1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnpjFCompraBusca1ActionPerformed

    private void txtCpfFCompraBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfFCompraBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfFCompraBuscaActionPerformed

    private void cbxProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprasVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprasVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprasVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprasVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprasVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarCompra;
    private javax.swing.JButton btnBuscarCompra;
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnExcluirCompra;
    private javax.swing.JButton btnLimparCompra;
    private javax.swing.JButton btnLimparCompraBusca;
    private javax.swing.JComboBox cbxFuncionarios1;
    private javax.swing.JComboBox cbxProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JFormattedTextField txtCnpjFCompra;
    private javax.swing.JFormattedTextField txtCnpjFCompraBusca1;
    private javax.swing.JFormattedTextField txtCpfFCompraBusca;
    private javax.swing.JTextField txtIDfornecimentoCompra;
    private javax.swing.JTextField txtIDfornecimentoCompraBusca;
    private javax.swing.JTextField txtQTDcompraBusca;
    private javax.swing.JTextField txtQTDprodutoCompra;
    private javax.swing.JTextField txt_identificadorProdutoCompraB;
    // End of variables declaration//GEN-END:variables
}
