/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import dto.Fornecedor;
import dao.FornecedorDAO;
import java.text.ParseException;
import javax.swing.JOptionPane;

public class FornecedorVIEW extends javax.swing.JFrame {

    public FornecedorVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTelFornecedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNomeFornecedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtEmailFornecedor = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        LimparFornecedor = new javax.swing.JButton();
        CadastrarFornecedor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCidadeFornecedor = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEnderecoFornecedor = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbxEstadoFornecedor = new javax.swing.JComboBox<>();
        txtCnpjFornecedor = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNomeFornecedorBusca = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEmailFornecedorBusca = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTELfornecedorBusca = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        btnBuscarFornecedor = new javax.swing.JButton();
        btnLimparFornecedorBusca = new javax.swing.JButton();
        btnDeletarFornecedor = new javax.swing.JButton();
        jButonAtualizarFornecedor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEnderecoFornecedorBusca = new javax.swing.JTextPane();
        txtCidadeFornecedorBusca = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEstadoFornecedorBusca = new javax.swing.JTextField();
        txtCnpjFornecedorBusca = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("CNPJ Fornecedor");

        jLabel2.setText("Nome Fornecedor");

        jLabel3.setText("Telefone");

        jLabel6.setText("Email");

        jLabel51.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel51.setText("Cadastrar Fornecedor");

        LimparFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar-limpo.png"))); // NOI18N
        LimparFornecedor.setText("Limpar");
        LimparFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparFornecedorActionPerformed(evt);
            }
        });

        CadastrarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mole.png"))); // NOI18N
        CadastrarFornecedor.setText("Cadastrar");
        CadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarFornecedorActionPerformed(evt);
            }
        });

        jLabel4.setText("Endereço");

        txtCidadeFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeFornecedorActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(txtEnderecoFornecedor);

        jLabel12.setText("Cidade");

        jLabel15.setText("Estado");

        cbxEstadoFornecedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SP", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SE", "TO", " ", " ", " ", " ", " ", " ", " " }));
        cbxEstadoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxEstadoFornecedorActionPerformed(evt);
            }
        });

        try {
            txtCnpjFornecedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpjFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnpjFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtCidadeFornecedor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbxEstadoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(LimparFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CadastrarFornecedor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 77, Short.MAX_VALUE))
                            .addComponent(txtCnpjFornecedor))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(txtTelFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCnpjFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidadeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEstadoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CadastrarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LimparFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        jLabel8.setText("CNPJ Fornecedor");

        jLabel9.setText("Nome Fornecedor");

        txtNomeFornecedorBusca.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setText("Email");

        txtEmailFornecedorBusca.setBackground(new java.awt.Color(204, 204, 204));

        jLabel13.setText("Telefone");

        txtTELfornecedorBusca.setBackground(new java.awt.Color(204, 204, 204));

        jLabel52.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel52.setText("Buscar Fornecedor");

        btnBuscarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/binoculars.png"))); // NOI18N
        btnBuscarFornecedor.setText("Buscar");
        btnBuscarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarFornecedorActionPerformed(evt);
            }
        });

        btnLimparFornecedorBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar-limpo.png"))); // NOI18N
        btnLimparFornecedorBusca.setText("Limpar");
        btnLimparFornecedorBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparFornecedorBuscaActionPerformed(evt);
            }
        });

        btnDeletarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        btnDeletarFornecedor.setText("Deletar");
        btnDeletarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarFornecedorActionPerformed(evt);
            }
        });

        jButonAtualizarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/updated.png"))); // NOI18N
        jButonAtualizarFornecedor.setText("Atualizar");
        jButonAtualizarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButonAtualizarFornecedorActionPerformed(evt);
            }
        });

        jLabel5.setText("Endereço");

        txtEnderecoFornecedorBusca.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(txtEnderecoFornecedorBusca);

        txtCidadeFornecedorBusca.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setText("Cidade");

        jLabel14.setText("Estado");

        txtEstadoFornecedorBusca.setBackground(new java.awt.Color(204, 204, 204));

        try {
            txtCnpjFornecedorBusca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpjFornecedorBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnpjFornecedorBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel52))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtCidadeFornecedorBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButonAtualizarFornecedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeletarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtEstadoFornecedorBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 103, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmailFornecedorBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(txtTELfornecedorBusca)))
                            .addComponent(txtNomeFornecedorBusca))
                        .addGap(75, 75, 75))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCnpjFornecedorBusca)
                        .addGap(32, 32, 32)
                        .addComponent(btnBuscarFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimparFornecedorBusca)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel52)
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCnpjFornecedorBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarFornecedor)
                    .addComponent(btnLimparFornecedorBusca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNomeFornecedorBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailFornecedorBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTELfornecedorBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCidadeFornecedorBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadoFornecedorBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButonAtualizarFornecedor)
                    .addComponent(btnDeletarFornecedor))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarFornecedorActionPerformed

        String cnpjFornecedor, nomeFornecedor, telefoneFornecedor, emailFornecedor, enderecoFornecedor, cidadeFornecedor, estadoFornecedor;

        cnpjFornecedor = txtCnpjFornecedor.getText();
        try {
            txtCnpjFornecedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (ParseException e) {
            e.printStackTrace();
        }
        nomeFornecedor = txtNomeFornecedor.getText();
        telefoneFornecedor = txtTelFornecedor.getText();
        emailFornecedor = txtEmailFornecedor.getText();
        enderecoFornecedor = txtEmailFornecedor.getText();
        cidadeFornecedor = txtCidadeFornecedor.getText();
        estadoFornecedor = cbxEstadoFornecedor.getSelectedItem().toString();

        Fornecedor novoFornecedor = new Fornecedor();

        novoFornecedor.setCnpjFornecedor(cnpjFornecedor);
        novoFornecedor.setNomeFornecedor(nomeFornecedor);
        novoFornecedor.setTelefoneFornecedor(telefoneFornecedor);
        novoFornecedor.setEmailFornecedor(emailFornecedor);
        novoFornecedor.setEnderecoFornecedor(enderecoFornecedor);
        novoFornecedor.setCidadeFornecedor(cidadeFornecedor);
        novoFornecedor.setEstadoFornecedor(estadoFornecedor);

        FornecedorDAO novoFornecedorDAO = new FornecedorDAO();
        boolean cadastrado = novoFornecedorDAO.cadastrarFornecedor(novoFornecedor);

        if (cadastrado) {
            JOptionPane.showMessageDialog(this, "Fornecedor cadastrado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar Fornecedor. Verifique os dados e tente novamente.");
        }


    }//GEN-LAST:event_CadastrarFornecedorActionPerformed

    private void btnLimparFornecedorBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFornecedorBuscaActionPerformed

        txtCidadeFornecedorBusca.setText("");
        txtCnpjFornecedorBusca.setText("");
        txtEmailFornecedorBusca.setText("");
        txtEnderecoFornecedorBusca.setText("");
        txtNomeFornecedorBusca.setText("");
        txtTELfornecedorBusca.setText("");
        txtEstadoFornecedorBusca.setText("");
    }//GEN-LAST:event_btnLimparFornecedorBuscaActionPerformed

    private void txtCidadeFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeFornecedorActionPerformed

    private void cbxEstadoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxEstadoFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxEstadoFornecedorActionPerformed

    private void txtCnpjFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnpjFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnpjFornecedorActionPerformed

    private void txtCnpjFornecedorBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnpjFornecedorBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnpjFornecedorBuscaActionPerformed

    private void btnBuscarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFornecedorActionPerformed

        String cnpjFornecedor = txtCnpjFornecedorBusca.getText();

        // Verificar se o cnpj foi digitado
        if (!cnpjFornecedor.isEmpty()) {
            FornecedorDAO fornecedordao = new FornecedorDAO();
            Fornecedor fornecedor = fornecedordao.buscarFornecedorPorCnpj(cnpjFornecedor);

            // Verificar se encontrou o fornecedor
            if (fornecedor != null) {
                // O fornecedor foi encontrado, desta forma ele seta os valores dos campos com os dados do respectivo funcionario.
                txtCnpjFornecedorBusca.setText(fornecedor.getCnpjFornecedor());
                txtNomeFornecedorBusca.setText(fornecedor.getNomeFornecedor());
                txtTELfornecedorBusca.setText(fornecedor.getTelefoneFornecedor());
                txtEmailFornecedorBusca.setText(fornecedor.getEmailFornecedor());
                txtEnderecoFornecedorBusca.setText(fornecedor.getEnderecoFornecedor());
                txtCidadeFornecedorBusca.setText(fornecedor.getCidadeFornecedor());
                txtEstadoFornecedorBusca.setText(fornecedor.getEstadoFornecedor());

                JOptionPane.showMessageDialog(null, "Fornecedor encontrado!");
            } else {
                // O funcionário não foi encontrado
                JOptionPane.showMessageDialog(null, "Fornecedor não encontrado!");
            }
        } else {
            // O CNPJ não foi digitado
            JOptionPane.showMessageDialog(null, "Digite um CNPJ válido!");
        }


    }//GEN-LAST:event_btnBuscarFornecedorActionPerformed

    private void jButonAtualizarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButonAtualizarFornecedorActionPerformed

        String CnpjFornecedor = txtCnpjFornecedorBusca.getText();
        FornecedorDAO fornecedorDAO = new FornecedorDAO();

        // Busca o funcionário pelo CPF
        Fornecedor fornecedor = fornecedorDAO.buscarFornecedorPorCnpj(CnpjFornecedor);

        if (fornecedor != null) {
            // Atualizar dados do fornecedor

            // Após atualizar os campos necessários, você pode criar um objeto Funcionario com os dados atualizados
            Fornecedor fornecedorAtualizado = new Fornecedor();
            
            fornecedorAtualizado.setCnpjFornecedor(CnpjFornecedor);
            fornecedorAtualizado.setNomeFornecedor(txtNomeFornecedorBusca.getText());
            fornecedorAtualizado.setTelefoneFornecedor(txtTELfornecedorBusca.getText());
            fornecedorAtualizado.setEmailFornecedor(txtEmailFornecedorBusca.getText());
            fornecedorAtualizado.setEnderecoFornecedor(txtEnderecoFornecedorBusca.getText());
            fornecedorAtualizado.setCidadeFornecedor(txtCidadeFornecedorBusca.getText());
            fornecedorAtualizado.setEstadoFornecedor(txtEstadoFornecedorBusca.getText());

            // ...
            // Realiza a atualização do funcionário
            boolean atualizado = fornecedorDAO.atualizarFornecedor(fornecedorAtualizado);

            if (atualizado) {
                JOptionPane.showMessageDialog(this, "Fornecedor atualizado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar Fornecedor. Verifique os dados e tente novamente.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Fornecedor não encontrado. Verifique o CNPJ e tente novamente.");
        }
    }//GEN-LAST:event_jButonAtualizarFornecedorActionPerformed

    private void btnDeletarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarFornecedorActionPerformed

        String cnpjFornecedor = txtCnpjFornecedorBusca.getText();// obtém o cnpj do fornecedor.
        FornecedorDAO fornecedor = new FornecedorDAO();
        boolean excluido = fornecedor.excluirFornecedorPorCNPJ(cnpjFornecedor);

        if (excluido) {
            JOptionPane.showMessageDialog(null, "Fornecedor Excluido com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao excluir Fornecedor. "
                    + "Verifique o CNPJ e tente novamente.");
        }


    }//GEN-LAST:event_btnDeletarFornecedorActionPerformed

    private void LimparFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparFornecedorActionPerformed
        txtCidadeFornecedor.setText("");
        txtCnpjFornecedor.setText("");
        txtEmailFornecedor.setText("");
        txtEnderecoFornecedor.setText("");
        txtNomeFornecedor.setText("");
        txtTelFornecedor.setText("");
    }//GEN-LAST:event_LimparFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FornecedorVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FornecedorVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FornecedorVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FornecedorVIEW.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FornecedorVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadastrarFornecedor;
    private javax.swing.JButton LimparFornecedor;
    private javax.swing.JButton btnBuscarFornecedor;
    private javax.swing.JButton btnDeletarFornecedor;
    private javax.swing.JButton btnLimparFornecedorBusca;
    private javax.swing.JComboBox<String> cbxEstadoFornecedor;
    private javax.swing.JButton jButonAtualizarFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCidadeFornecedor;
    private javax.swing.JTextField txtCidadeFornecedorBusca;
    private javax.swing.JFormattedTextField txtCnpjFornecedor;
    private javax.swing.JFormattedTextField txtCnpjFornecedorBusca;
    private javax.swing.JTextField txtEmailFornecedor;
    private javax.swing.JTextField txtEmailFornecedorBusca;
    private javax.swing.JTextPane txtEnderecoFornecedor;
    private javax.swing.JTextPane txtEnderecoFornecedorBusca;
    private javax.swing.JTextField txtEstadoFornecedorBusca;
    private javax.swing.JTextField txtNomeFornecedor;
    private javax.swing.JTextField txtNomeFornecedorBusca;
    private javax.swing.JTextField txtTELfornecedorBusca;
    private javax.swing.JTextField txtTelFornecedor;
    // End of variables declaration//GEN-END:variables
}
