/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.JLabel;

/**
 *
 * @author jedle
 */
public class Loading extends javax.swing.JFrame {

    private static Loading instance;
    private static JProgressBar progressBar;
    private static JLabel percentageLabel;

    /**
     * Creates new form Loading
     */
    public Loading() {
        initComponents();
        progressBar = barraDeProgresso;
        percentageLabel = porcentagem;
    }

    public static Loading getLoadingInstance() {
        if (instance == null) {
            instance = new Loading();
        }
        return instance;
    }

    public static JProgressBar getProgressBar() {
        return progressBar;
    }

    public static JLabel getPercentageLabel() {
        return percentageLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        barraDeProgresso = new javax.swing.JProgressBar();
        porcentagem = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));
        jPanel1.add(barraDeProgresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 280, 30));

        porcentagem.setFont(new java.awt.Font("DialogInput", 3, 18)); // NOI18N
        porcentagem.setText("99");
        jPanel1.add(porcentagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/HamburguerGIF.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        Loading loading = new Loading();
        loading.setVisible(true);
        try {
            for (int i = 0; i <= 100; i += 3) {
                Thread.sleep(70);
                loading.barraDeProgresso.setValue(i);
                loading.porcentagem.setText(Integer.toString(i) + "%");

            }
            loading.dispose();

            MenuVIEW novoMenu = new MenuVIEW();
            novoMenu.setVisible(true);

        } catch (InterruptedException e) {
            JOptionPane.showConfirmDialog(null, "erro");

        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar barraDeProgresso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel porcentagem;
    // End of variables declaration//GEN-END:variables
}
