/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import dto.ProdutoDTO;
import dao.ProdutoDAO;
import java.text.ParseException;
import javax.swing.JOptionPane;

public class ProdutoVIEW extends javax.swing.JFrame {

    /**
     * Creates new form ProdutoVIEW
     */
    public ProdutoVIEW() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCODprodutoIdentificador = new javax.swing.JTextField();
        txtNomeProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMarcaProduto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCategoriaProduto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecoProduto = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        btnLimparProduto = new javax.swing.JButton();
        btnCadastrarProduto = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtQTDproduto = new javax.swing.JTextField();
        txtCnpjFProduto = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCod_identificadorProdutoBusca = new javax.swing.JTextField();
        txtNomeProdutoBusca = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtMarcaProdutoBusca = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCategoriaProdutoBusca = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtprecoProdutoBusca = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnBuscarProduto = new javax.swing.JButton();
        btnLimparProdutoBusca = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        btnAtualizarProduto = new javax.swing.JButton();
        txtQTDprodutoBusca = new javax.swing.JTextField();
        txtCnpjFProdutoBusca = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Código Identificador");

        jLabel2.setText("Nome do Produto:");

        jLabel3.setText("CNPJ Fornecedor:");

        txtCODprodutoIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCODprodutoIdentificadorActionPerformed(evt);
            }
        });

        jLabel4.setText("Categoria:");

        jLabel5.setText("Marca:");

        jLabel6.setText("Preço:");

        jLabel51.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel51.setText("Cadastrar Produto");

        btnLimparProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar-limpo.png"))); // NOI18N
        btnLimparProduto.setText("Limpar");
        btnLimparProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparProdutoActionPerformed(evt);
            }
        });

        btnCadastrarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mole.png"))); // NOI18N
        btnCadastrarProduto.setText("Cadastrar");
        btnCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarProdutoActionPerformed(evt);
            }
        });

        jLabel7.setText("Quantidade");

        txtQTDproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQTDprodutoActionPerformed(evt);
            }
        });

        try {
            txtCnpjFProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpjFProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnpjFProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCODprodutoIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(txtCnpjFProduto)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMarcaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(txtQTDproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnLimparProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCadastrarProduto))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel51)))
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCODprodutoIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCnpjFProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMarcaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQTDproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLimparProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadastrarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        jLabel8.setText("Código Identificador");

        jLabel9.setText("Nome do Produto:");

        jLabel10.setText("CNPJ Fornecedor:");

        txtNomeProdutoBusca.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setText("Categoria:");

        txtMarcaProdutoBusca.setBackground(new java.awt.Color(204, 204, 204));

        jLabel12.setText("Marca:");

        txtCategoriaProdutoBusca.setBackground(new java.awt.Color(204, 204, 204));

        jLabel13.setText("Preço:");

        txtprecoProdutoBusca.setBackground(new java.awt.Color(204, 204, 204));

        jLabel52.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        jLabel52.setText("Buscar Produto");

        jLabel14.setText("Quantidade");

        btnBuscarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/binoculars.png"))); // NOI18N
        btnBuscarProduto.setText("Buscar");
        btnBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdutoActionPerformed(evt);
            }
        });

        btnLimparProdutoBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar-limpo.png"))); // NOI18N
        btnLimparProdutoBusca.setText("Limpar");
        btnLimparProdutoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparProdutoBuscaActionPerformed(evt);
            }
        });

        btnExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        btnExcluirProduto.setText("Deletar");
        btnExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdutoActionPerformed(evt);
            }
        });

        btnAtualizarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/updated.png"))); // NOI18N
        btnAtualizarProduto.setText("Atualizar");
        btnAtualizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarProdutoActionPerformed(evt);
            }
        });

        txtQTDprodutoBusca.setBackground(new java.awt.Color(204, 204, 204));

        txtCnpjFProdutoBusca.setEditable(false);
        txtCnpjFProdutoBusca.setBackground(new java.awt.Color(204, 204, 204));
        try {
            txtCnpjFProdutoBusca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpjFProdutoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCnpjFProdutoBuscaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnAtualizarProduto)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtMarcaProdutoBusca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                        .addComponent(txtNomeProdutoBusca, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(txtCod_identificadorProdutoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCnpjFProdutoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnBuscarProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLimparProdutoBusca))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel11)
                                .addComponent(jLabel14)
                                .addComponent(txtQTDprodutoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtprecoProdutoBusca, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(txtCategoriaProdutoBusca))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel52)))
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel52)
                .addGap(34, 34, 34)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCod_identificadorProdutoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimparProdutoBusca)
                    .addComponent(btnBuscarProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeProdutoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecoProdutoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtCategoriaProdutoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtMarcaProdutoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtQTDprodutoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCnpjFProdutoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAtualizarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed

        String codigo_identificador_produto, nome_produto, categoria_produto, marca_produto, preco_produto, cnpj_fornecedor, qtd_produto;

        codigo_identificador_produto = txtCODprodutoIdentificador.getText();
        nome_produto = txtNomeProduto.getText();
        categoria_produto = txtCategoriaProduto.getText();
        marca_produto = txtMarcaProduto.getText();
        preco_produto = txtPrecoProduto.getText();
        cnpj_fornecedor = txtCnpjFProduto.getText();
        qtd_produto = txtQTDproduto.getText();

        ProdutoDTO novoProduto = new ProdutoDTO();

        novoProduto.setCodigo_identificador_produto(codigo_identificador_produto);
        novoProduto.setNome_produto(nome_produto);
        novoProduto.setCategoria_produto(categoria_produto);
        novoProduto.setMarca_produto(marca_produto);
        novoProduto.setPreco_produto(preco_produto);
        novoProduto.setCnpj_fornecedor(cnpj_fornecedor);
        novoProduto.setQtd_Produto(qtd_produto);

        ProdutoDAO novoProdutoDAO = new ProdutoDAO();
        boolean cadastrado = novoProdutoDAO.cadastrarProduto(novoProduto);

        if (cadastrado) {
            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar produto. Verifique os dados e tente novamente.");
        }


    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void btnLimparProdutoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparProdutoBuscaActionPerformed

        txtCategoriaProdutoBusca.setText("");
        txtCod_identificadorProdutoBusca.setText("");
        txtCnpjFProdutoBusca.setText("");
        txtMarcaProdutoBusca.setText("");
        txtNomeProdutoBusca.setText("");
        txtprecoProdutoBusca.setText("");
        txtQTDprodutoBusca.setText("");
    }//GEN-LAST:event_btnLimparProdutoBuscaActionPerformed

    private void txtQTDprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQTDprodutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQTDprodutoActionPerformed

    private void txtCnpjFProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnpjFProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnpjFProdutoActionPerformed

    private void txtCnpjFProdutoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCnpjFProdutoBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCnpjFProdutoBuscaActionPerformed

    private void txtCODprodutoIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCODprodutoIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCODprodutoIdentificadorActionPerformed

    private void btnBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdutoActionPerformed

        String codigo_identificador_produto = txtCod_identificadorProdutoBusca.getText();

        // Verificar se o Código identificador foi digitado
        if (!codigo_identificador_produto.isEmpty()) {
            ProdutoDAO produtoDAO = new ProdutoDAO();
            ProdutoDTO produtoEncontrado = produtoDAO.buscarProduto(codigo_identificador_produto);

            // Verificar se encontrou o ptoduto
            if (produtoEncontrado != null) {
                // O produto foi encontrado, desta forma ele seta os valores dos campos com os dados do respectivo funcionario.
                txtNomeProdutoBusca.setText(produtoEncontrado.getNome_produto());
                txtCategoriaProdutoBusca.setText(produtoEncontrado.getCategoria_produto());
                txtMarcaProdutoBusca.setText(produtoEncontrado.getMarca_produto());
                txtprecoProdutoBusca.setText(produtoEncontrado.getPreco_produto());
                txtCnpjFProdutoBusca.setText(produtoEncontrado.getCnpj_fornecedor());
                txtQTDprodutoBusca.setText(produtoEncontrado.getQtd_Produto());

                JOptionPane.showMessageDialog(null, "Produto encontrado!");
            } else {
                // O produto não foi encontrado
                JOptionPane.showMessageDialog(null, "Produto não encontrado!");
            }
        } else {
            // O código identificador não foi digitado
            JOptionPane.showMessageDialog(null, "Digite um Código Identificador válido!");
        }


    }//GEN-LAST:event_btnBuscarProdutoActionPerformed

    private void btnLimparProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparProdutoActionPerformed

        txtCategoriaProduto.setText("");
        txtCODprodutoIdentificador.setText("");
        txtCnpjFProduto.setText("");
        txtMarcaProduto.setText("");
        txtNomeProduto.setText("");
        txtPrecoProduto.setText("");
        txtQTDproduto.setText("");
    }//GEN-LAST:event_btnLimparProdutoActionPerformed

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed

        String codigo_identificador_produto = txtCod_identificadorProdutoBusca.getText();

        ProdutoDAO produtodao = new ProdutoDAO();

        boolean excluido = produtodao.excluirProdutoPorCODidentificador(codigo_identificador_produto);

        if (excluido) {
            JOptionPane.showMessageDialog(this, "Produto excluido com sucesso.");
        } else {
            JOptionPane.showMessageDialog(this, "Falha ao excluir Produto, "
                    + "verifique o código Identificador e tente novamente.");
        }
    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void btnAtualizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarProdutoActionPerformed

        String codigo_identificador_produto = txtCod_identificadorProdutoBusca.getText();
        ProdutoDAO produtodao = new ProdutoDAO();

        // Busca o produto pelo Código Identificador
        ProdutoDTO produtodto = produtodao.buscarProduto(codigo_identificador_produto);

        if (produtodto != null) {
            // Atualizar dados do fornecedor

            // Após atualizar os campos necessários, você pode criar um objeto Funcionario com os dados atualizados
            ProdutoDTO produtoAtualizado = new ProdutoDTO();

            produtoAtualizado.setCodigo_identificador_produto(codigo_identificador_produto);
            produtoAtualizado.setNome_produto(txtNomeProdutoBusca.getText());
            produtoAtualizado.setCategoria_produto(txtCategoriaProdutoBusca.getText());
            produtoAtualizado.setMarca_produto(txtMarcaProdutoBusca.getText());
            produtoAtualizado.setPreco_produto(txtprecoProdutoBusca.getText());
            produtoAtualizado.setCnpj_fornecedor(txtCnpjFProdutoBusca.getText());
            produtoAtualizado.setQtd_Produto(txtQTDprodutoBusca.getText());
            // ...
            // Realiza a atualização do funcionário
            boolean atualizado = produtodao.atualizarProduto(produtoAtualizado);

            if (atualizado) {
                JOptionPane.showMessageDialog(this, "Produto atualizado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao atualizar Produto. Verifique os dados e tente novamente.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Produto não encontrado. Verifique o Código identificador e tente novamente.");
        }
    }

    private void btnDeletarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {

  

    }//GEN-LAST:event_btnAtualizarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoVIEW.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoVIEW.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoVIEW.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoVIEW.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoVIEW().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarProduto;
    private javax.swing.JButton btnBuscarProduto;
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnLimparProduto;
    private javax.swing.JButton btnLimparProdutoBusca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCODprodutoIdentificador;
    private javax.swing.JTextField txtCategoriaProduto;
    private javax.swing.JTextField txtCategoriaProdutoBusca;
    private javax.swing.JFormattedTextField txtCnpjFProduto;
    private javax.swing.JFormattedTextField txtCnpjFProdutoBusca;
    private javax.swing.JTextField txtCod_identificadorProdutoBusca;
    private javax.swing.JTextField txtMarcaProduto;
    private javax.swing.JTextField txtMarcaProdutoBusca;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtNomeProdutoBusca;
    private javax.swing.JTextField txtPrecoProduto;
    private javax.swing.JTextField txtQTDproduto;
    private javax.swing.JTextField txtQTDprodutoBusca;
    private javax.swing.JTextField txtprecoProdutoBusca;
    // End of variables declaration//GEN-END:variables
}
